spring:
  application:
    name: generator
  main:
    web-application-type: none

generator:
  count: 100
  batch-size: 10
  initiator: GENERATOR

document-service:
  url: http://localhost:80/api/v1
