server:
  port: 80
  servlet:
    context-path: /api/v1
logging:
  level:
    root: info
  file:
    name: spam_logs

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/documents
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:123}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          default_batch_fetch_size: 50
  liquibase:
    change-log: classpath:liquibase/master.xml

worker:
  batch-size: 50
  submit:
    cron: "*/50 * * * * *"
  approve:
    cron: "*/58 * * * * *"
  initiator: "WORKER"

