plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'document-service'

ext {
    mapstructVersion = '1.5.5.Final'
    lombokMapstructBindingVersion = '0.2.0'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'com.h2database:h2'

    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${lombokMapstructBindingVersion}"
}

bootJar {
    enabled = true
    archiveFileName = 'document-service.jar'
}

jar {
    enabled = false
}
